name: CD

on:
    push:
        branches:
          - main
jobs:
    deploy:
        runs-on: ubuntu-latest
        
        steps:
          - name: Trigger deployment on Render platform
            env:
              RENDER_DEPLOY_HOOK_URL: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
            run: |
              curl -X POST "$RENDER_DEPLOY_HOOK_URL"